baseURL: https://www.hugobricks.preview.usecue.com
theme: hugobricks
defaultContentLanguage: en
assetDir: static

markup:
  goldmark:
    renderer:
      unsafe: true # Allow HTML in md files
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2


languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
    disabled: false